apiVersion: apps/v1
kind: Deployment
metadata:
  name: wigo

spec:
  #replicas: 3
  selector:
    matchLabels:
      app: wigo

  template:
    metadata:
      labels:
        app: wigo

    spec:
      containers:
      - name: wigo 
        image: wigo-img:latest 
        imagePullPolicy: Never

        ports:
          - containerPort: 4000

        resources:
          requests:
            cpu: 100m     # 10% of a cpu core
            memory: 200Mi # 200mb RAM

        livenessProbe:
          httpGet:
            path: /hc
            port: 4000 
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5

        readinessProbe:
          httpGet:
            path: /hc
            port: 4000 
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
